// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Networking;
using System;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var temperatures = Temperatures.FromJson(jsonString);

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using quickType;
//
//    var temperatures = Temperatures.FromJson(jsonString);

namespace quickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Temperatures
    {
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public long? Status { get; set; }

        [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
        public string Message { get; set; }

        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public Datum[] Data { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("initialStep", NullValueHandling = NullValueHandling.Ignore)]
        public string InitialStep { get; set; }

        [JsonProperty("steps")]
        public Dictionary<string, Step> Steps { get; set; }

        /*[JsonProperty("steps", NullValueHandling = NullValueHandling.Ignore)]
        public Steps Steps { get; set; }*/

        [JsonProperty("estimatedDuration", NullValueHandling = NullValueHandling.Ignore)]
        public EstimatedDuration EstimatedDuration { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
        public long? Version { get; set; }

        [JsonProperty("labels", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Labels { get; set; }

        [JsonProperty("users", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Users { get; set; }

        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }
    }

    public partial class EstimatedDuration
    {
        [JsonProperty("minutes", NullValueHandling = NullValueHandling.Ignore)]
        public long? Minutes { get; set; }

        [JsonProperty("hours", NullValueHandling = NullValueHandling.Ignore)]
        public long? Hours { get; set; }
    }

    public partial class Step
    {
        [JsonProperty("data")]
        public StepData Data { get; set; }
    }

    public partial class StepData
    {
        [JsonProperty("selected")]
        public bool Selected { get; set; }

        [JsonProperty("template")]
        public Template Template { get; set; }

        [JsonProperty("editNameMode")]
        public bool EditNameMode { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }

        [JsonProperty("layouts")]
        public Layout[] Layouts { get; set; }

        [JsonProperty("show")]
        public bool Show { get; set; }
    }

    public partial class Layout
    {
        [JsonProperty("items")]
        public Item[] Items { get; set; }
    }

    public partial class Item
    {
        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("templateOptions")]
        public TemplateOptions TemplateOptions { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class TemplateOptions
    {
        [JsonProperty("position")]
        public PositionEnum Position { get; set; }

        [JsonProperty("options")]
        public Option[] Options { get; set; }

        [JsonProperty("qrfield")]
        public string Qrfield { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("hPosition")]
        public Position HPosition { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("placeholder")]
        public string Placeholder { get; set; }

        [JsonProperty("vPosition")]
        public Position VPosition { get; set; }

        [JsonProperty("required")]
        public bool TemplateOptionsRequired { get; set; }

        [JsonProperty("max")]
        public long? Max { get; set; }

        [JsonProperty("precision")]
        public long? Precision { get; set; }

        [JsonProperty("videoUrl")]
        public string VideoUrl { get; set; }

        [JsonProperty("imgUrl")]
        public string ImgUrl { get; set; }

        [JsonProperty("disabled")]
        public bool Disabled { get; set; }

        [JsonProperty("unit")]
        public Unit Unit { get; set; }

        [JsonProperty("min")]
        public long? Min { get; set; }
    }

    public enum Position { Center };

    public enum PositionEnum { Centered };

    public enum Unit { C, Empty };

    /*public partial class Steps
    {
        [JsonProperty("KKW050VGbkFTUMRtZvPg", NullValueHandling = NullValueHandling.Ignore)]
        public Kkw050VGbkFtumRtZvPg Kkw050VGbkFtumRtZvPg { get; set; }

        [JsonProperty("rAuiSa2ksdNWG773vaAV", NullValueHandling = NullValueHandling.Ignore)]
        public RAuiSa2KsdNwg773VaAv RAuiSa2KsdNwg773VaAv { get; set; }

        [JsonProperty("KKSSpW9SJFE2ACddwvFG", NullValueHandling = NullValueHandling.Ignore)]
        public BpbXhhpg6Gey2QGyyQk2 KksSpW9Sjfe2ACddwvFg { get; set; }

        [JsonProperty("vFMvov2dp58nSG3Di4mH", NullValueHandling = NullValueHandling.Ignore)]
        public UwDmt6Trn6FfWenXjItR VFMvov2Dp58NSg3Di4MH { get; set; }

        [JsonProperty("2EIjenPrMt3bT1jLup4H", NullValueHandling = NullValueHandling.Ignore)]
        public The2EIjenPrMt3BT1JLup4H The2EIjenPrMt3BT1JLup4H { get; set; }

        [JsonProperty("GTXoUxjrUtZhIySiqx0i", NullValueHandling = NullValueHandling.Ignore)]
        public GtXoUxjrUtZhIySiqx0I GtXoUxjrUtZhIySiqx0I { get; set; }

        [JsonProperty("ACjrkvbtL5KjbgUOmiFF", NullValueHandling = NullValueHandling.Ignore)]
        public ACjrkvbtL5KjbgUOmiFf ACjrkvbtL5KjbgUOmiFf { get; set; }

        [JsonProperty("BpbXHHPG6Gey2qGYYQk2", NullValueHandling = NullValueHandling.Ignore)]
        public BpbXhhpg6Gey2QGyyQk2 BpbXhhpg6Gey2QGyyQk2 { get; set; }

        [JsonProperty("j1XVVxItoU2j4IKKdFfl", NullValueHandling = NullValueHandling.Ignore)]
        public PbqXvm23MAao03PCqK3U J1XvVxItoU2J4IkKdFfl { get; set; }

        [JsonProperty("AucvQN7xzdB3IKc4jHCz", NullValueHandling = NullValueHandling.Ignore)]
        public AucvQn7XzdB3IKc4JHCz AucvQn7XzdB3IKc4JHCz { get; set; }

        [JsonProperty("YgiDCw23ggOEsT0dJY4K", NullValueHandling = NullValueHandling.Ignore)]
        public BpbXhhpg6Gey2QGyyQk2 YgiDCw23GgOEsT0DJy4K { get; set; }

        [JsonProperty("VrmWuN6cuYdmPR8w1FWO", NullValueHandling = NullValueHandling.Ignore)]
        public VrmWuN6CuYdmPr8W1Fwo VrmWuN6CuYdmPr8W1Fwo { get; set; }

        [JsonProperty("SnV3DJ5dHnKEO2wW5RXG", NullValueHandling = NullValueHandling.Ignore)]
        public BpbXhhpg6Gey2QGyyQk2 SnV3Dj5DHnKeo2WW5Rxg { get; set; }

        [JsonProperty("EiXoqwrQZGfvg7D6DHRh", NullValueHandling = NullValueHandling.Ignore)]
        public BpbXhhpg6Gey2QGyyQk2 EiXoqwrQzGfvg7D6DhRh { get; set; }

        [JsonProperty("TnacKPfpO1MZpDc6tUIX", NullValueHandling = NullValueHandling.Ignore)]
        public BpbXhhpg6Gey2QGyyQk2 TnacKPfpO1MZpDc6TUix { get; set; }

        [JsonProperty("dV9SELcI4rN3N9L2KQY8", NullValueHandling = NullValueHandling.Ignore)]
        public AucvQn7XzdB3IKc4JHCz DV9SeLcI4RN3N9L2Kqy8 { get; set; }

        [JsonProperty("UwDmt6TRN6FFWenXjItR", NullValueHandling = NullValueHandling.Ignore)]
        public UwDmt6Trn6FfWenXjItR UwDmt6Trn6FfWenXjItR { get; set; }

        [JsonProperty("PBQXvm23mAAO03pCqK3U", NullValueHandling = NullValueHandling.Ignore)]
        public PbqXvm23MAao03PCqK3U PbqXvm23MAao03PCqK3U { get; set; }

        [JsonProperty("BScnhw4vt12fpxBNSt3p", NullValueHandling = NullValueHandling.Ignore)]
        public BScnhw4Vt12FpxBnSt3P BScnhw4Vt12FpxBnSt3P { get; set; }

        [JsonProperty("qbXqEbAA0lwEZPT3rXjt", NullValueHandling = NullValueHandling.Ignore)]
        public BpbXhhpg6Gey2QGyyQk2 QbXqEbAa0LwEzpt3RXjt { get; set; }

        [JsonProperty("UBpnfJUvxBsLEzE6xHmV", NullValueHandling = NullValueHandling.Ignore)]
        public BpbXhhpg6Gey2QGyyQk2 UBpnfJUvxBsLEzE6XHmV { get; set; }

        [JsonProperty("xjfEAHLBaPBU2l8rR81l", NullValueHandling = NullValueHandling.Ignore)]
        public PbqXvm23MAao03PCqK3U XjfEahlBaPbu2L8RR81L { get; set; }

        [JsonProperty("MSiaxAOmtZ3NkWEVBvhO", NullValueHandling = NullValueHandling.Ignore)]
        public BpbXhhpg6Gey2QGyyQk2 MSiaxAOmtZ3NkWevBvhO { get; set; }
    }
    */
    public partial class ACjrkvbtL5KjbgUOmiFf
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public ACjrkvbtL5KjbgUOmiFfData Data { get; set; }
    }

    public partial class ACjrkvbtL5KjbgUOmiFfData
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }

        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public FluffyLayout[] Layouts { get; set; }

        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }
    }

    public partial class FluffyLayout
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public FluffyItem[] Items { get; set; }
    }

    public partial class FluffyItem
    {
        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("templateOptions", NullValueHandling = NullValueHandling.Ignore)]
        public FluffyTemplateOptions TemplateOptions { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public TypeEnum? Type { get; set; }
    }

    public partial class FluffyTemplateOptions
    {
        [JsonProperty("hPosition", NullValueHandling = NullValueHandling.Ignore)]
        public string HPosition { get; set; }

        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("vPosition", NullValueHandling = NullValueHandling.Ignore)]
        public string VPosition { get; set; }
    }

    public partial class Template
    {
        [JsonProperty("orientation", NullValueHandling = NullValueHandling.Ignore)]
        public Orientation? Orientation { get; set; }

        [JsonProperty("weights", NullValueHandling = NullValueHandling.Ignore)]
        public long[] Weights { get; set; }

        [JsonProperty("count", NullValueHandling = NullValueHandling.Ignore)]
        public long? Count { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public Name? Name { get; set; }
    }

    public partial class AucvQn7XzdB3IKc4JHCz
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public AucvQn7XzdB3IKc4JHCzData Data { get; set; }
    }

    public partial class AucvQn7XzdB3IKc4JHCzData
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }

        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }

        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }

        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public TentacledLayout[] Layouts { get; set; }

        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }
    }

    public partial class TentacledLayout
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public TentacledItem[] Items { get; set; }
    }

    public partial class TentacledItem
    {
        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("templateOptions", NullValueHandling = NullValueHandling.Ignore)]
        public TentacledTemplateOptions TemplateOptions { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }
    }

    public partial class TentacledTemplateOptions
    {
        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public bool? TemplateOptionsRequired { get; set; }

        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("options", NullValueHandling = NullValueHandling.Ignore)]
        public Option[] Options { get; set; }

        [JsonProperty("imgName", NullValueHandling = NullValueHandling.Ignore)]
        public string ImgName { get; set; }

        [JsonProperty("imgUrl", NullValueHandling = NullValueHandling.Ignore)]
        public Uri ImgUrl { get; set; }
    }

    public partial class Option
    {
        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        public string Value { get; set; }

        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }
    }

    public partial class BScnhw4Vt12FpxBnSt3P
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public BScnhw4Vt12FpxBnSt3PData Data { get; set; }
    }

    public partial class BScnhw4Vt12FpxBnSt3PData
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public StickyLayout[] Layouts { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }

        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }

        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }
    }

    public partial class StickyLayout
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public StickyItem[] Items { get; set; }
    }

    public partial class StickyItem
    {
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("templateOptions", NullValueHandling = NullValueHandling.Ignore)]
        public StickyTemplateOptions TemplateOptions { get; set; }
    }

    public partial class StickyTemplateOptions
    {
        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public bool? TemplateOptionsRequired { get; set; }

        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("qrfield", NullValueHandling = NullValueHandling.Ignore)]
        public string Qrfield { get; set; }
    }

    public partial class BpbXhhpg6Gey2QGyyQk2
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public BpbXhhpg6Gey2QGyyQk2Data Data { get; set; }
    }

    public partial class BpbXhhpg6Gey2QGyyQk2Data
    {
        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public IndigoLayout[] Layouts { get; set; }

        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }

        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }

        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }
    }

    public partial class IndigoLayout
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public IndigoItem[] Items { get; set; }
    }

    public partial class IndigoItem
    {
        [JsonProperty("templateOptions", NullValueHandling = NullValueHandling.Ignore)]
        public IndigoTemplateOptions TemplateOptions { get; set; }

        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public TypeEnum? Type { get; set; }
    }

    public partial class IndigoTemplateOptions
    {
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("hPosition", NullValueHandling = NullValueHandling.Ignore)]
        public string HPosition { get; set; }

        [JsonProperty("vPosition", NullValueHandling = NullValueHandling.Ignore)]
        public string VPosition { get; set; }

        [JsonProperty("imgName", NullValueHandling = NullValueHandling.Ignore)]
        public string ImgName { get; set; }

        [JsonProperty("imgUrl", NullValueHandling = NullValueHandling.Ignore)]
        public Uri ImgUrl { get; set; }
    }

    public partial class GtXoUxjrUtZhIySiqx0I
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public GtXoUxjrUtZhIySiqx0IData Data { get; set; }
    }

    public partial class GtXoUxjrUtZhIySiqx0IData
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public IndecentLayout[] Layouts { get; set; }

        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }

        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }
    }

    public partial class IndecentLayout
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public IndecentItem[] Items { get; set; }
    }

    public partial class IndecentItem
    {
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("templateOptions", NullValueHandling = NullValueHandling.Ignore)]
        public IndecentTemplateOptions TemplateOptions { get; set; }
    }

    public partial class IndecentTemplateOptions
    {
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("min", NullValueHandling = NullValueHandling.Ignore)]
        public long? Min { get; set; }

        [JsonProperty("precision")]
        public long? Precision { get; set; }

        [JsonProperty("max", NullValueHandling = NullValueHandling.Ignore)]
        public long? Max { get; set; }

        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public bool? TemplateOptionsRequired { get; set; }

        [JsonProperty("placeholder", NullValueHandling = NullValueHandling.Ignore)]
        public string Placeholder { get; set; }

        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore)]
        public string Unit { get; set; }
    }

    public partial class PbqXvm23MAao03PCqK3U
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public PbqXvm23MAao03PCqK3UData Data { get; set; }
    }

    public partial class PbqXvm23MAao03PCqK3UData
    {
        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }

        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }

        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public HilariousLayout[] Layouts { get; set; }

        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }
    }

    public partial class HilariousLayout
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public HilariousItem[] Items { get; set; }
    }

    public partial class HilariousItem
    {
        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("templateOptions", NullValueHandling = NullValueHandling.Ignore)]
        public HilariousTemplateOptions TemplateOptions { get; set; }
    }

    public partial class HilariousTemplateOptions
    {
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public bool? TemplateOptionsRequired { get; set; }

        [JsonProperty("timepicker", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Timepicker { get; set; }

        [JsonProperty("placeholder", NullValueHandling = NullValueHandling.Ignore)]
        public string Placeholder { get; set; }
    }

    public partial class Kkw050VGbkFtumRtZvPg
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public Kkw050VGbkFtumRtZvPgData Data { get; set; }
    }

    public partial class Kkw050VGbkFtumRtZvPgData
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }

        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }

        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public IndecentLayout[] Layouts { get; set; }
    }

    public partial class RAuiSa2KsdNwg773VaAv
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public RAuiSa2KsdNwg773VaAvData Data { get; set; }
    }

    public partial class RAuiSa2KsdNwg773VaAvData
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }

        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public MagentaLayout[] Layouts { get; set; }

        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }

        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }
    }

    public partial class MagentaLayout
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public MagentaItem[] Items { get; set; }
    }

    public partial class MagentaItem
    {
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("templateOptions", NullValueHandling = NullValueHandling.Ignore)]
        public MagentaTemplateOptions TemplateOptions { get; set; }

        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }
    }

    public partial class MagentaTemplateOptions
    {
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("videoUrl", NullValueHandling = NullValueHandling.Ignore)]
        public Uri VideoUrl { get; set; }

        [JsonProperty("videoName", NullValueHandling = NullValueHandling.Ignore)]
        public string VideoName { get; set; }
    }

    public partial class The2EIjenPrMt3BT1JLup4H
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public The2EIjenPrMt3BT1JLup4HData Data { get; set; }
    }

    public partial class The2EIjenPrMt3BT1JLup4HData
    {
        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }

        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public PurpleLayout[] Layouts { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }
    }

    public partial class PurpleLayout
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public PurpleItem[] Items { get; set; }
    }

    public partial class PurpleItem
    {
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("templateOptions", NullValueHandling = NullValueHandling.Ignore)]
        public PurpleTemplateOptions TemplateOptions { get; set; }
    }

    public partial class PurpleTemplateOptions
    {
        [JsonProperty("vPosition", NullValueHandling = NullValueHandling.Ignore)]
        public string VPosition { get; set; }

        [JsonProperty("hPosition", NullValueHandling = NullValueHandling.Ignore)]
        public string HPosition { get; set; }

        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public bool? TemplateOptionsRequired { get; set; }

        [JsonProperty("options", NullValueHandling = NullValueHandling.Ignore)]
        public Option[] Options { get; set; }
    }

    public partial class UwDmt6Trn6FfWenXjItR
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public UwDmt6Trn6FfWenXjItRData Data { get; set; }
    }

    public partial class UwDmt6Trn6FfWenXjItRData
    {
        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }

        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public AmbitiousLayout[] Layouts { get; set; }

        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }

        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }
    }

    public partial class AmbitiousLayout
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public AmbitiousItem[] Items { get; set; }
    }

    public partial class AmbitiousItem
    {
        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("templateOptions", NullValueHandling = NullValueHandling.Ignore)]
        public AmbitiousTemplateOptions TemplateOptions { get; set; }
    }

    public partial class AmbitiousTemplateOptions
    {
        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public bool? TemplateOptionsRequired { get; set; }

        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }
    }

    public partial class VrmWuN6CuYdmPr8W1Fwo
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public VrmWuN6CuYdmPr8W1FwoData Data { get; set; }
    }

    public partial class VrmWuN6CuYdmPr8W1FwoData
    {
        [JsonProperty("next", NullValueHandling = NullValueHandling.Ignore)]
        public string Next { get; set; }

        [JsonProperty("show", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Show { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("layouts", NullValueHandling = NullValueHandling.Ignore)]
        public CunningLayout[] Layouts { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("editNameMode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EditNameMode { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }
    }

    public partial class CunningLayout
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public CunningItem[] Items { get; set; }
    }

    public partial class CunningItem
    {
        [JsonProperty("templateOptions", NullValueHandling = NullValueHandling.Ignore)]
        public CunningTemplateOptions TemplateOptions { get; set; }

        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public TypeEnum? Type { get; set; }
    }

    public partial class CunningTemplateOptions
    {
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("imgUrl", NullValueHandling = NullValueHandling.Ignore)]
        public Uri ImgUrl { get; set; }

        [JsonProperty("imgName", NullValueHandling = NullValueHandling.Ignore)]
        public string ImgName { get; set; }
    }

    public enum TypeEnum { Image, Label };

    public enum Name { Fullscreen, HorizontalEqual, VerticalEqual };

    public enum Orientation { Column, Row };

    public partial class Temperatures
    {
        public static Temperatures FromJson(string json) => JsonConvert.DeserializeObject<Temperatures>(json, quickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Temperatures self) => JsonConvert.SerializeObject(self, quickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                NameConverter.Singleton,
                OrientationConverter.Singleton,
                TypeEnumConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class NameConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Name) || t == typeof(Name?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "fullscreen":
                    return Name.Fullscreen;
                case "horizontal-equal":
                    return Name.HorizontalEqual;
                case "vertical-equal":
                    return Name.VerticalEqual;
            }
            throw new Exception("Cannot unmarshal type Name");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Name)untypedValue;
            switch (value)
            {
                case Name.Fullscreen:
                    serializer.Serialize(writer, "fullscreen");
                    return;
                case Name.HorizontalEqual:
                    serializer.Serialize(writer, "horizontal-equal");
                    return;
                case Name.VerticalEqual:
                    serializer.Serialize(writer, "vertical-equal");
                    return;
            }
            throw new Exception("Cannot marshal type Name");
        }

        public static readonly NameConverter Singleton = new NameConverter();
    }

    internal class OrientationConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Orientation) || t == typeof(Orientation?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "column":
                    return Orientation.Column;
                case "row":
                    return Orientation.Row;
            }
            throw new Exception("Cannot unmarshal type Orientation");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Orientation)untypedValue;
            switch (value)
            {
                case Orientation.Column:
                    serializer.Serialize(writer, "column");
                    return;
                case Orientation.Row:
                    serializer.Serialize(writer, "row");
                    return;
            }
            throw new Exception("Cannot marshal type Orientation");
        }

        public static readonly OrientationConverter Singleton = new OrientationConverter();
    }

    internal class TypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum) || t == typeof(TypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "image":
                    return TypeEnum.Image;
                case "label":
                    return TypeEnum.Label;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (TypeEnum)untypedValue;
            switch (value)
            {
                case TypeEnum.Image:
                    serializer.Serialize(writer, "image");
                    return;
                case TypeEnum.Label:
                    serializer.Serialize(writer, "label");
                    return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }
}

public class Header : MonoBehaviour
{
    string UnityUrl = "https://demo0173267.mockable.io";
    InputField outputArea;

    public void Start()
    {
        outputArea = GameObject.Find("OutputArea").GetComponent<InputField>();
        if (outputArea == null)
            Debug.Log("It is null");
        GameObject.Find("GetButton").GetComponent<Button>().onClick.AddListener(GetData);
    }

    public void GetData() => StartCoroutine(GetData_Coroutine());

    public IEnumerator GetData_Coroutine()
    {
        outputArea.text = "Loading...";
        string uri = UnityUrl;
        using (UnityWebRequest request = UnityWebRequest.Get(uri))
        {
            yield return request.SendWebRequest();
            if (request.isNetworkError || request.isHttpError)
                outputArea.text = request.error;
            else
            {
                string temp = request.downloadHandler.text;

                outputArea.text = request.downloadHandler.text;
            }
        }
    }
}

//using namespace QuickType;
/*public class RootClass
{    
    public List<QuickType.Welcome> welcome_ { get; set; }
    public List<QuickType.WelcomeData> welcomeData_ { get; set; }
    public List<QuickType.Step> step_ { get; set; }
    public List<QuickType.StepData> stepData_ { get; set; }
    public List<QuickType.Layout> layout_ { get; set; }
    public List<QuickType.Item> item_ { get; set; }
    public List<QuickType.TemplateOptions> templateOptions_ { get; set; }
    public List<QuickType.Option> option_ { get; set; }
    public List<QuickType.Template> template_ { get; set; }
    //public List<List<QuickType.PositionConverter>> pos_ { get; set; }

}*/